const customPurchaseItems = [
  // {
  //   itemName: 'one-hour-consultation',
  //   title: 'One-hour consultation',
  //   price: 1000,
  //   description:
  //     'Get advice from a former law school admissions officer via phone, zoom, email, or a combo—your choice. Each hour comes with a free proofread of any admissions document',
  //   isMultiple: false,
  //   isSoldOut: false,
  //   maxLimit: null,
  //   details: [
  //     'Receive expert guidance from a former law school admissions officer on an hourly basis.',
  //     'Use your time for strategic consultation about your app or feedback on any stage of any essay.',
  //     'Total flexibility. Talk via phone, Zoom, email, or some combination—it’s up to you.',
  //     '48-hour response time.',
  //     'Includes a final review of one document from our in-house proofreading team.',
  //     'Includes access to the 7SageAdmissions Course.',
  //   ],
  // },
  // {
  //   itemName: 'mock-application-review',
  //   title: 'Mock application review',
  //   price: 1000,
  //   description:
  //     'Have your entire application for one law school reviewed by a former admissions officer. Includes cover-to-cover strategic feedback, an hour-long follow-up call, and free proofreading of the whole application. ',
  //   isMultiple: false,
  //   isSoldOut: false,
  //   maxLimit: null,
  //   details: [
  //     'Comprehensive review of one application by a former law school admissions officer.',
  //     'Receive detailed feedback and actionable suggestions.',
  //     'Includes one hour-long follow-up call.',
  //     '48-hour turnaround time.',
  //     'Includes a final pass from our in-house proofreading team for each document.',
  //     'Includes access to the 7SageAdmissions Course.',
  //   ],
  // },
  // {
  //   itemName: 'five-school-admissions-package',
  //   title: '5-school admissions package',
  //   price: 1000,
  //   description:
  //     'Start-to-finish guidance on your personal statement, diversity statement, résumé, Why X essays, and addenda.',
  //   isMultiple: false,
  //   isSoldOut: false,
  //   maxLimit: null,
  //   details: [
  //     'Expert guidance on applications to five schools.',
  //     'Start-to-finish guidance on your personal statement, diversity statement, résumé, Why X essays, addenda, C&F disclosures, in-app short answers, and more. ',
  //     'Unlimited calls, unlimited emails.',
  //     '48-hour turnaround time.',
  //     'Includes a final pass from our in-house proofreading team for each document.',
  //     'Includes access to the 7Sage Admissions Course.',
  //   ],
  // },
  // {
  //   itemName: 'single-edit-essay',
  //   title: 'Single edit of an essay',
  //   price: 1000,
  //   description:
  //     'Have your personal statement, résumé, or any other law school admissions document professionally edited.',
  //   isMultiple: false,
  //   isSoldOut: false,
  //   maxLimit: null,
  //   details: [
  //     'One round of editorial feedback on an admissions document of your choice.',
  //     'You can choose an overall critique with major suggestions for revision or a sentence-level edit for language, style, grammar, and syntax—or leave it up to your editor. ',
  //     '48-hour turnaround time.',
  //     'Includes a final pass from our in-house proofreading team.',
  //     'Includes access to the 7Sage Admissions Course.',
  //   ],
  // },
  {
    itemName: 'unlimited-edit-essay',
    title: 'Unlimited edit of an essay',
    price: 1000,
    description:
      'Receive ongoing editorial feedback from a published author for as long as it takes to polish one admissions document. We can work with you on an essay you’ve already begun, or else help you start from scratch. ',
    isMultiple: false,
    isSoldOut: false,
    maxLimit: null,
    details: [
      'Start-to-finish help on any law school admissions document, including personal statements, diversity statements, Why X’s, optional statements, résumés, and addenda.',
      'We’ll help you at any stage of the process, from brainstorming a topic to revise an existing draft.',
      '48-hour turnaround per round of revisions.',
      'Includes a final pass from our in-house proofreading team for each document.',
      'Includes access to the 7Sage Admissions Course.',
    ],
  },
  {
    itemName: 'five-school-writing-package',
    title: '5-school writing package',
    price: 1000,
    description:
      'As many rounds of feedback as you need on all your written materials for up to five law school applications—including personal statement, résumé, diversity statement, addenda, Why X statements, in-app short answers, and more.',
    isMultiple: false,
    isSoldOut: false,
    maxLimit: null,
    details: [
      'Start-to-finish help on any law school admissions document, including personal statements, diversity statements, Why X’s, optional statements, résumés, and addenda.',
      '48-hour turnaround time.',
      '48-hour turnaround per round of revisions.',
      'Includes a final pass from our in-house proofreading team for each document.',
      'Includes access to the 7Sage Admissions Course.',
    ],
  },
  {
    itemName: 'item-sold-out',
    title: '5-school writing package',
    price: 1000,
    description:
      'As many rounds of feedback as you need on all your written materials for up to five law school applications—including personal statement, résumé, diversity statement, addenda, Why X statements, in-app short answers, and more.',
    isMultiple: false,
    isSoldOut: true,
    maxLimit: null,
    details: [
      'Start-to-finish help on any law school admissions document, including personal statements, diversity statements, Why X’s, optional statements, résumés, and addenda.',
      'We’ll help you at any stage of the process, from brainstorming a topic to revise an existing draft.',
      '48-hour turnaround per round of revisions.',
      'Includes a final pass from our in-house proofreading team for each document.',
      'Includes access to the 7Sage Admissions Course.',
    ],
  },
  {
    itemName: 'item-multiple',
    title: '5-school writing package',
    price: 1000,
    description:
      'Receive ongoing editorial feedback from a published author for as long as it takes to polish one admissions document. We can work with you on an essay you’ve already begun, or else help you start from scratch. ',
    isMultiple: true,
    isSoldOut: false,
    maxLimit: 3,
    details: [
      'Start-to-finish help on any law school admissions document, including personal statements, diversity statements, Why X’s, optional statements, résumés, and addenda.',
      'We’ll help you at any stage of the process, from brainstorming a topic to revise an existing draft.',
      '48-hour turnaround per round of revisions.',
      'Includes a final pass from our in-house proofreading team for each document.',
      'Includes access to the 7Sage Admissions Course.',
    ],
  },
];
export default customPurchaseItems;
